/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "cal.h"

calculator_res *
calculator_1_svc(operation arg1,  struct svc_req *rqstp)
{
	static calculator_res  result;

	/*
	 * insert server code here
	 */

	return &result;
}

calculator_res *
calculator_2_svc(operation arg1,  struct svc_req *rqstp)
{
	static calculator_res  result;

	/*
	 * insert server code here
	 */

	return &result;
}
