/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "cal.h"

bool_t
xdr_vector_t (XDR *xdrs, vector_t *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->vector_t_val, (u_int *) &objp->vector_t_len, MAX_SIZE,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_matrix (XDR *xdrs, matrix *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->matrix_val, (u_int *) &objp->matrix_len, MAX_SIZE,
		sizeof (vector_t), (xdrproc_t) xdr_vector_t))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_operatorType (XDR *xdrs, operatorType *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAX))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_operation (XDR *xdrs, operation *objp)
{
	register int32_t *buf;

	 if (!xdr_Operation (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_operationMatrix (XDR *xdrs, operationMatrix *objp)
{
	register int32_t *buf;

	 if (!xdr_OperationMatrix (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Operation (XDR *xdrs, Operation *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->firstNumber))
		 return FALSE;
	 if (!xdr_operatorType (xdrs, &objp->operator))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->secondNumber))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_calculator_res (XDR *xdrs, calculator_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->errnum))
		 return FALSE;
	switch (objp->errnum) {
	case 0:
		 if (!xdr_double (xdrs, &objp->calculator_res_u.res))
			 return FALSE;
		break;
	case 1:
		break;
	default:
		break;
	}
	return TRUE;
}
